site_name: junior.guru
site_url: https://junior.guru/


nav:
  - Příručka:
      - Úvod: handbook/index.md
      - Motivace: handbook/motivation.md
      - Základy: handbook/learn.md
      - Řešení problémů: handbook/help.md
      - První praxe: handbook/practice.md
      - Psychika: handbook/mental-health.md
      - Git a GitHub: handbook/git.md
      - Hledání práce: handbook/candidate.md
      - Životopis: handbook/cv.md
      - LinkedIn: handbook/linkedin.md
  - Podcast: podcast.md
  - Práce: jobs/
  - Klub: club.md
  - Pravidla:
      - Otázky a odpovědi: faq.md
      - Pravidla chování: coc.md
      - Obchodní podmínky: tos.md
      - Zásady ochrany osobních údajů: privacy.md
      - Čísla a grafy: open.md
      - Licence obsahu (CC BY-SA): https://creativecommons.org/licenses/by-sa/4.0/deed.cs
  - Témata:
      - ... | flat | topics/*.md
  - Partnerství:
      - ... | flat | open/*.md
  - Ostatní:
      - ... | flat


markdown_extensions:
  - toc:
      toc_depth: '2-2'
      permalink: '#'
      permalink_title: Odkaz na tuto sekci
  - tables
  - fenced_code
  - attr_list


theme:
  name: null
  custom_dir: theme/


hooks:
  - hooks.py


plugins:
  - gen-files:
      scripts:
        - templates.py
  - awesome-pages:
      strict: true


# Removed 'strict', because it gives warnings if linking non-existing targets. Once the Flask
# app is gone, 'strict' should return to be enabled.
#strict: true
