version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"
